#!/usr/bin/env bun
/**
 * Extract the xxHash64 seed from a Claude Code binary.
 *
 * Fully automated: downloads the binary from npm, generates oracle pairs
 * by running the binary against a local capture server, then scans the
 * binary for the seed that satisfies all oracle pairs.
 *
 * Usage:
 *   # Fully automated — download + generate oracles + extract
 *   bun run scripts/extract-cch-seed.ts --version 2.1.138
 *
 *   # Use a local binary — generate oracles + extract
 *   bun run scripts/extract-cch-seed.ts --binary ./claude
 *
 *   # Legacy mode — use pre-captured oracle pairs
 *   bun run scripts/extract-cch-seed.ts --version 2.1.138 --oracle pairs.json
 *   bun run scripts/extract-cch-seed.ts --binary ./claude --oracle pairs.json
 *
 *   # Apply extracted seed to cch.ts
 *   bun run scripts/extract-cch-seed.ts --apply 2.1.138 0x4D659218E32A3268
 *
 * Oracle pairs JSON format (for --oracle):
 *   [
 *     { "body": "{...cch=00000...}", "cch": "a39d0" },
 *     { "body": "{...cch=00000...}", "cch": "6fc47" }
 *   ]
 *
 * The script:
 *   1. Downloads the platform-matching binary from npm (or uses --binary)
 *   2. Generates oracle pairs by running the binary against a local HTTP server
 *   3. Tests every 8-byte aligned offset as a candidate seed
 *   4. Falls back to 1-byte aligned scan if no 8-byte match found
 *   5. Reports the seed ready for VERSION_SEEDS in cch.ts
 *
 * Performance: ~16s for 8-byte scan, ~5min for 1-byte fallback (230MB binary).
 * Two oracle pairs eliminate all false positives (1-in-2^40 collision).
 */

import { readFileSync, existsSync, mkdirSync, unlinkSync, writeFileSync } from "fs";
import { execSync } from "child_process";
import { parseArgs } from "util";

// ---------------------------------------------------------------------------
// CLI argument parsing
// ---------------------------------------------------------------------------

const { values: args, positionals } = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    version: { type: "string", short: "v" },
    binary: { type: "string", short: "b" },
    oracle: { type: "string", short: "o" },
    output: { type: "string" },
    apply: { type: "boolean" },
    help: { type: "boolean", short: "h" },
  },
  allowPositionals: true,
});

if (args.help) {
  console.log(`Usage:
  bun run scripts/extract-cch-seed.ts --version <VERSION>
  bun run scripts/extract-cch-seed.ts --binary <path>
  bun run scripts/extract-cch-seed.ts --version <VERSION> --oracle <pairs.json>
  bun run scripts/extract-cch-seed.ts --apply <VERSION> <SEED_HEX>

Options:
  -v, --version   Claude Code version to download from npm (e.g. 2.1.138)
  -b, --binary    Path to existing binary (must match host platform)
  -o, --oracle    Path to pre-captured oracle pairs JSON (skips auto-generation)
  --output        Write result as JSON to this path
  --apply         Apply a seed to packages/gateway/src/cch.ts (positional: VERSION SEED)
  -h, --help      Show this help

When --oracle is omitted, oracle pairs are auto-generated by running the Claude
Code binary against a local capture server. Requires the binary to be executable
on the current platform.

Oracle pairs JSON format:
  [{"body": "...body with cch=00000...", "cch": "a39d0"}, ...]`);
  process.exit(0);
}

// ---------------------------------------------------------------------------
// --apply mode: patch cch.ts with a new seed
// ---------------------------------------------------------------------------

if (args.apply) {
  if (positionals.length < 2) {
    console.error("Usage: --apply <VERSION> <SEED_HEX>");
    console.error("  e.g. --apply 2.1.138 0x4D659218E32A3268");
    process.exit(1);
  }
  const [version, seedHex] = positionals;
  applySeed(version, seedHex);
  process.exit(0);
}

if (!args.version && !args.binary) {
  console.error("Either --version or --binary is required. Use --help for usage.");
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface OraclePair {
  body: string;
  cch: string;
}

// ---------------------------------------------------------------------------
// Oracle pair generation via capture server
// ---------------------------------------------------------------------------

const PROMPTS = [
  "hello",
  "what is the meaning of life?",
  "explain quantum computing in one sentence",
];

async function generateOraclePairs(
  binaryPath: string,
  count: number = 2,
): Promise<OraclePair[]> {
  console.log(`\nGenerating ${count} oracle pair(s) via capture server...`);

  const pairs: OraclePair[] = [];
  const tmpDir = "/tmp/cch-oracle-gen";
  mkdirSync(tmpDir, { recursive: true });
  mkdirSync(`${tmpDir}/home`, { recursive: true });
  mkdirSync(`${tmpDir}/workdir`, { recursive: true });
  // .keep so Claude Code doesn't error on empty workdir
  writeFileSync(`${tmpDir}/workdir/.keep`, "");

  for (let i = 0; i < count && i < PROMPTS.length; i++) {
    const prompt = PROMPTS[i];
    console.log(`  Pair ${i + 1}: prompt="${prompt}"`);

    const pair = await captureOnePair(binaryPath, prompt, tmpDir);
    if (pair) {
      pairs.push(pair);
      console.log(`    cch=${pair.cch}, body=${pair.body.length} bytes`);
    } else {
      console.error(`    Failed to capture oracle pair for prompt "${prompt}"`);
    }
  }

  if (pairs.length < 2) {
    console.error(
      `\nOnly captured ${pairs.length} oracle pair(s). Need at least 2 to eliminate false positives.`,
    );
    if (pairs.length === 0) process.exit(1);
    console.warn("WARNING: Proceeding with 1 pair — expect false positives (~11)");
  }

  return pairs;
}

async function captureOnePair(
  binaryPath: string,
  prompt: string,
  tmpDir: string,
): Promise<OraclePair | null> {
  let captured: OraclePair | null = null;

  const server = Bun.serve({
    port: 0, // ephemeral port
    async fetch(req) {
      if (req.method === "HEAD") {
        return new Response(null, { status: 200 });
      }

      const body = await req.text();
      if (!captured) {
        const cchMatch = body.match(/cch=([0-9a-f]{5})/);
        if (cchMatch) {
          const placeholder = body.replace(
            `cch=${cchMatch[1]}`,
            "cch=00000",
          );
          captured = { body: placeholder, cch: cchMatch[1] };
        }
      }

      return Response.json(
        {
          type: "error",
          error: {
            type: "authentication_error",
            message: "invalid x-api-key",
          },
        },
        { status: 401 },
      );
    },
  });

  try {
    const proc = Bun.spawn(
      [binaryPath, "--print", "--bare", "-p", prompt],
      {
        env: {
          ...process.env,
          HOME: `${tmpDir}/home`,
          ANTHROPIC_API_KEY:
            "sk-ant-api03-fakekey1234567890abcdef1234567890abcdef1234567890abcdef",
          ANTHROPIC_BASE_URL: `http://127.0.0.1:${server.port}`,
          DISABLE_AUTOUPDATER: "1",
          DISABLE_UPDATES: "1",
        },
        cwd: `${tmpDir}/workdir`,
        stdout: "ignore",
        stderr: "ignore",
      },
    );

    // Wait up to 15s for the binary to make its request
    const timeout = setTimeout(() => proc.kill(), 15_000);
    await proc.exited;
    clearTimeout(timeout);
  } finally {
    server.stop();
  }

  return captured;
}

// ---------------------------------------------------------------------------
// Load oracle pairs from file
// ---------------------------------------------------------------------------

function loadOraclePairs(path: string): OraclePair[] {
  if (!existsSync(path)) {
    console.error(`Oracle file not found: ${path}`);
    process.exit(1);
  }

  const pairs: OraclePair[] = JSON.parse(readFileSync(path, "utf-8"));
  if (!Array.isArray(pairs) || pairs.length === 0) {
    console.error("Oracle file must contain a non-empty JSON array");
    process.exit(1);
  }

  for (const [i, pair] of pairs.entries()) {
    if (!pair.body || !pair.cch) {
      console.error(`Oracle pair ${i} missing 'body' or 'cch' field`);
      process.exit(1);
    }
    if (!pair.body.includes("cch=00000")) {
      console.error(
        `Oracle pair ${i} body must contain 'cch=00000' placeholder`,
      );
      process.exit(1);
    }
    if (!/^[0-9a-f]{5}$/.test(pair.cch)) {
      console.error(
        `Oracle pair ${i} cch must be a 5-char lowercase hex string, got: ${pair.cch}`,
      );
      process.exit(1);
    }
  }

  return pairs;
}

// ---------------------------------------------------------------------------
// Obtain binary
// ---------------------------------------------------------------------------

function detectPlatformPackage(): string {
  const platform = process.platform; // darwin, linux, win32
  const arch = process.arch; // x64, arm64
  return `@anthropic-ai/claude-code-${platform}-${arch}`;
}

function obtainBinary(version?: string, binaryPath?: string): string {
  if (binaryPath) {
    if (!existsSync(binaryPath)) {
      console.error(`Binary not found: ${binaryPath}`);
      process.exit(1);
    }
    return binaryPath;
  }

  const pkg = `${detectPlatformPackage()}@${version}`;
  const tmpDir = "/tmp/cch-seed-extract";
  mkdirSync(tmpDir, { recursive: true });

  console.log(`Downloading ${pkg} from npm...`);
  try {
    execSync(`npm pack ${pkg} --pack-destination ${tmpDir}`, {
      stdio: ["pipe", "pipe", "pipe"],
      cwd: tmpDir,
    });
  } catch (e: any) {
    console.error(`Failed to download ${pkg}: ${e.message}`);
    process.exit(1);
  }

  // Find the tarball
  const tgzGlob = new Bun.Glob("anthropic-ai-claude-code-*-*.tgz");
  let tgzPath = "";
  for (const file of tgzGlob.scanSync(tmpDir)) {
    tgzPath = `${tmpDir}/${file}`;
    break;
  }
  if (!tgzPath) {
    console.error("Could not find downloaded tarball");
    process.exit(1);
  }

  console.log("Extracting binary from tarball...");
  execSync(`tar xzf "${tgzPath}" -C "${tmpDir}"`, { stdio: "pipe" });

  const extractedBinary = `${tmpDir}/package/claude`;
  const extractedBinaryExe = `${tmpDir}/package/claude.exe`;
  const finalPath = existsSync(extractedBinary)
    ? extractedBinary
    : existsSync(extractedBinaryExe)
      ? extractedBinaryExe
      : null;

  if (!finalPath) {
    console.error(`Expected binary at ${extractedBinary} after extraction`);
    process.exit(1);
  }

  // Make executable
  try {
    execSync(`chmod +x "${finalPath}"`, { stdio: "pipe" });
  } catch {}

  // Clean up tarball
  try {
    unlinkSync(tgzPath);
  } catch {}

  return finalPath;
}

// ---------------------------------------------------------------------------
// Scan for seed
// ---------------------------------------------------------------------------

function testCandidate(seed: bigint, pairs: OraclePair[]): boolean {
  for (const pair of pairs) {
    const hash = Bun.hash.xxHash64(pair.body, seed);
    const cch = (hash & 0xFFFFFn).toString(16).padStart(5, "0");
    if (cch !== pair.cch) return false;
  }
  return true;
}

function scan(
  binary: Buffer,
  pairs: OraclePair[],
  alignment: number,
): bigint | null {
  const candidates = Math.floor((binary.length - 7) / alignment);
  const label = alignment === 8 ? "8-byte aligned" : "1-byte aligned";
  console.log(
    `\nScanning ${candidates.toLocaleString()} ${label} candidates...`,
  );

  const start = performance.now();
  let tested = 0;
  const matches: Array<{ offset: number; seed: bigint }> = [];

  for (let offset = 0; offset + 8 <= binary.length; offset += alignment) {
    const candidate = binary.readBigUInt64LE(offset);
    if (candidate === 0n) continue;

    if (testCandidate(candidate, pairs)) {
      matches.push({ offset, seed: candidate });
      console.log(
        `  MATCH at offset 0x${offset.toString(16)}: seed = 0x${candidate.toString(16).padStart(16, "0")}`,
      );
      // With 2+ pairs, first match is almost certainly unique
      if (pairs.length >= 2) break;
    }
    tested++;
  }

  const elapsed = performance.now() - start;
  console.log(
    `Scan complete: ${tested.toLocaleString()} tested in ${(elapsed / 1000).toFixed(1)}s`,
  );

  if (matches.length === 0) {
    console.log("No matches found.");
    return null;
  }

  if (matches.length === 1 || pairs.length >= 2) {
    const m = matches[0];
    console.log(
      `\n✓ Found seed: 0x${m.seed.toString(16).padStart(16, "0")}`,
    );
    return m.seed;
  }

  console.log(
    `\n⚠ Found ${matches.length} matches — add more oracle pairs to disambiguate`,
  );
  return null;
}

function scanForSeed(binary: Buffer, pairs: OraclePair[]): bigint | null {
  // Try 8-byte aligned first (fast)
  let seed = scan(binary, pairs, 8);

  // Fall back to 1-byte aligned if needed
  if (seed === null) {
    console.log("\nFalling back to 1-byte aligned scan...");
    seed = scan(binary, pairs, 1);
  }

  return seed;
}

// ---------------------------------------------------------------------------
// Apply seed to cch.ts
// ---------------------------------------------------------------------------

function applySeed(version: string, seedHex: string): void {
  // Normalize seed format
  const seed = seedHex.startsWith("0x") ? seedHex : `0x${seedHex}`;
  const seedUpper = seed.replace(/0x/i, "0x").replace(
    /[0-9a-f]+/i,
    (m) => m.toUpperCase(),
  );

  const cchPath = new URL(
    "../packages/gateway/src/cch.ts",
    import.meta.url,
  ).pathname;

  if (!existsSync(cchPath)) {
    console.error(`Cannot find cch.ts at: ${cchPath}`);
    process.exit(1);
  }

  let content = readFileSync(cchPath, "utf-8");

  // Check if version already exists
  if (content.includes(`"${version}"`)) {
    console.log(`Version ${version} already exists in VERSION_SEEDS. Updating...`);
    // Replace existing entry
    const entryRe = new RegExp(
      `"${version.replace(/\./g, "\\.")}":\\s*0x[0-9A-Fa-f]+n`,
    );
    content = content.replace(entryRe, `"${version}": ${seedUpper}n`);
  } else {
    // Add before the "Future versions" comment
    content = content.replace(
      /(\s*\/\/ Future versions: extract and add entries here\.)/,
      `  "${version}": ${seedUpper}n,\n$1`,
    );
  }

  // Update WORKER_VERSION
  content = content.replace(
    /const WORKER_VERSION = "[^"]+"/,
    `const WORKER_VERSION = "${version}"`,
  );

  writeFileSync(cchPath, content);
  console.log(`Updated ${cchPath}:`);
  console.log(`  VERSION_SEEDS["${version}"] = ${seedUpper}n`);
  console.log(`  WORKER_VERSION = "${version}"`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const binaryPath = obtainBinary(args.version, args.binary);
  const binary = readFileSync(binaryPath);
  console.log(
    `Binary: ${binaryPath} (${(binary.length / 1024 / 1024).toFixed(1)} MB)`,
  );

  // Get oracle pairs: from file or auto-generate
  let pairs: OraclePair[];
  if (args.oracle) {
    pairs = loadOraclePairs(args.oracle);
    console.log(`Loaded ${pairs.length} oracle pair(s) from ${args.oracle}`);
    if (pairs.length < 2) {
      console.warn(
        "WARNING: <2 oracle pairs — expect false positives (~11 per pair)",
      );
    }
  } else {
    pairs = await generateOraclePairs(binaryPath, 2);
  }

  // Scan
  const seed = scanForSeed(binary, pairs);

  if (seed !== null) {
    const hex = seed.toString(16).padStart(16, "0").toUpperCase();
    const version = args.version ?? "UNKNOWN";
    console.log(`
================================================================================
Add this to VERSION_SEEDS in packages/gateway/src/cch.ts:

  "${version}": 0x${hex}n,

Then update WORKER_VERSION if pinning to this version.

Or run:
  bun run scripts/extract-cch-seed.ts --apply "${version}" "0x${hex}"
================================================================================`);

    // Write JSON output if requested
    if (args.output) {
      const result = {
        version,
        seed: `0x${hex}`,
        seedDecimal: seed.toString(),
        oraclePairsUsed: pairs.length,
      };
      writeFileSync(args.output, JSON.stringify(result, null, 2));
      console.log(`Result written to ${args.output}`);
    }
  } else {
    console.error(
      "\nFailed to find seed. Possible causes:\n" +
        "  - Oracle pair generation failed (binary didn't make API calls)\n" +
        "  - Seed is constructed at runtime (not stored as raw bytes)\n" +
        "  - Binary is for the wrong platform/version",
    );
    process.exit(1);
  }
}

await main();
