#!/usr/bin/env node
/**
 * Extract the xxHash64 seed from a Claude Code binary.
 *
 * Fully automated: downloads the binary from npm, generates oracle pairs
 * by running the binary against a local capture server, then scans the
 * binary for the seed that satisfies all oracle pairs.
 *
 * Runs under Node.js (>= 22.5) via built-in TypeScript type-stripping — no
 * bundler or `tsx` required. Relative imports use explicit `.ts` extensions
 * because native Node does not resolve extensionless module specifiers.
 *
 * Usage:
 *   # Fully automated — download + generate oracles + extract
 *   node scripts/extract-cch-seed.ts --version 2.1.138
 *
 *   # Use a local binary — generate oracles + extract
 *   node scripts/extract-cch-seed.ts --binary ./claude
 *
 *   # Legacy mode — use pre-captured oracle pairs
 *   node scripts/extract-cch-seed.ts --version 2.1.138 --oracle pairs.json
 *   node scripts/extract-cch-seed.ts --binary ./claude --oracle pairs.json
 *
 *   # Apply extracted seed to cch.ts
 *   node scripts/extract-cch-seed.ts --apply 2.1.138 0x4D659218E32A3268
 *
 * Oracle pairs JSON format (for --oracle):
 *   [
 *     { "body": "{...cch=00000...}", "cch": "a39d0" },
 *     { "body": "{...cch=00000...}", "cch": "6fc47" }
 *   ]
 *
 * The script:
 *   1. Downloads the platform-matching binary from npm (or uses --binary)
 *   2. Generates oracle pairs by running the binary against a local HTTP server
 *   3. Tests every 8-byte aligned offset as a candidate seed
 *   4. Falls back to 1-byte aligned scan if no 8-byte match found
 *   5. Reports the seed ready for VERSION_SEEDS in cch.ts
 *
 * Performance: ~16s for 8-byte scan, ~5min for 1-byte fallback (230MB binary).
 * Two oracle pairs eliminate all false positives (1-in-2^40 collision).
 */

import {
  readFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { execSync, spawn, spawnSync } from "node:child_process";
import { createServer } from "node:http";
import type { AddressInfo } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { xxHash64 } from "../packages/gateway/src/xxhash.ts";
import { VERSION_SEEDS } from "../packages/gateway/src/cch.ts";

// ---------------------------------------------------------------------------
// CLI argument parsing
// ---------------------------------------------------------------------------

const { values: args, positionals } = parseArgs({
  args: process.argv.slice(2),
  options: {
    version: { type: "string", short: "v" },
    binary: { type: "string", short: "b" },
    oracle: { type: "string", short: "o" },
    output: { type: "string" },
    apply: { type: "boolean" },
    "no-pin": { type: "boolean" },
    help: { type: "boolean", short: "h" },
  },
  allowPositionals: true,
});

if (args.help) {
  console.log(`Usage:
  node scripts/extract-cch-seed.ts --version <VERSION>
  node scripts/extract-cch-seed.ts --binary <path>
  node scripts/extract-cch-seed.ts --version <VERSION> --oracle <pairs.json>
  node scripts/extract-cch-seed.ts --apply <VERSION> <SEED_HEX>
  node scripts/extract-cch-seed.ts --apply --no-pin <VERSION> <SEED_HEX>

Options:
  -v, --version   Claude Code version to download from npm (e.g. 2.1.138)
  -b, --binary    Path to existing binary (must match host platform)
  -o, --oracle    Path to pre-captured oracle pairs JSON (skips auto-generation)
  --output        Write result as JSON to this path
  --apply         Apply a seed to packages/gateway/src/cch.ts (positional: VERSION SEED)
  --no-pin        With --apply: add seed entry without updating WORKER_VERSION
  -h, --help      Show this help

When --oracle is omitted, oracle pairs are auto-generated by running the Claude
Code binary against a local capture server. Requires the binary to be executable
on the current platform.

Oracle pairs JSON format:
  [{"body": "...body with cch=00000...", "cch": "a39d0"}, ...]`);
  process.exit(0);
}

// ---------------------------------------------------------------------------
// --apply mode: patch cch.ts with a new seed
// ---------------------------------------------------------------------------

if (args.apply) {
  if (positionals.length < 2) {
    console.error("Usage: --apply [--no-pin] <VERSION> <SEED_HEX>");
    console.error("  e.g. --apply 2.1.138 0x4D659218E32A3268");
    process.exit(1);
  }
  const [version, seedHex] = positionals;
  applySeed(version, seedHex, { pin: !args["no-pin"] });
  process.exit(0);
}

if (!args.version && !args.binary) {
  console.error(
    "Either --version or --binary is required. Use --help for usage.",
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface OraclePair {
  /**
   * Raw request-body bytes with the `cch` field set to the `cch=00000`
   * placeholder. MUST be the exact bytes the client transmitted — never a
   * string round-trip. The body contains multibyte UTF-8 (e.g. `→` in tool
   * descriptions); decoding it to a JS string via `chunk.toString()` and
   * re-encoding corrupts any multibyte sequence split across a TCP chunk
   * boundary (each fragment becomes U+FFFD), which makes the hash unrecoverable.
   */
  body: Uint8Array;
  cch: string;
}

// ---------------------------------------------------------------------------
// Oracle pair generation via capture server
// ---------------------------------------------------------------------------

const PROMPTS = [
  "hello",
  "what is the meaning of life?",
  "explain quantum computing in one sentence",
];

async function generateOraclePairs(
  binaryPath: string,
  count: number = 2,
): Promise<OraclePair[]> {
  console.log(`\nGenerating ${count} oracle pair(s) via capture server...`);

  const pairs: OraclePair[] = [];
  const tmpDir = "/tmp/cch-oracle-gen";
  mkdirSync(tmpDir, { recursive: true });
  mkdirSync(`${tmpDir}/home`, { recursive: true });
  mkdirSync(`${tmpDir}/workdir`, { recursive: true });
  // .keep so Claude Code doesn't error on empty workdir
  writeFileSync(`${tmpDir}/workdir/.keep`, "");

  for (let i = 0; i < count && i < PROMPTS.length; i++) {
    const prompt = PROMPTS[i];
    console.log(`  Pair ${i + 1}: prompt="${prompt}"`);

    const pair = await captureOnePair(binaryPath, prompt, tmpDir);
    if (pair) {
      pairs.push(pair);
      console.log(`    cch=${pair.cch}, body=${pair.body.length} bytes`);
    } else {
      console.error(`    Failed to capture oracle pair for prompt "${prompt}"`);
    }
  }

  if (pairs.length < 2) {
    console.error(
      `\nOnly captured ${pairs.length} oracle pair(s). Need at least 2 to eliminate false positives.`,
    );
    if (pairs.length === 0) process.exit(1);
    console.warn(
      "WARNING: Proceeding with 1 pair — expect false positives (~11)",
    );
  }

  return pairs;
}

async function captureOnePair(
  binaryPath: string,
  prompt: string,
  tmpDir: string,
): Promise<OraclePair | null> {
  let captured: OraclePair | null = null;

  const server = createServer(async (req, res) => {
    if (req.method === "HEAD") {
      res.writeHead(200);
      res.end();
      return;
    }

    // Collect the raw body bytes (NEVER `body += chunk`, which UTF-8-decodes
    // each Buffer and corrupts multibyte sequences split across chunks).
    const chunks: Buffer[] = [];
    for await (const chunk of req) {
      chunks.push(chunk as Buffer);
    }
    const bodyBytes = Buffer.concat(chunks);

    if (!captured) {
      // The `cch=XXXXX` field is pure ASCII, so a latin1 view is byte-exact
      // for locating it without disturbing surrounding multibyte content.
      // NOTE: we target the FIRST `cch=<hex>` occurrence — the billing header is
      // the first system block, matching how Claude Code itself writes the cch.
      const cchMatch = bodyBytes.toString("latin1").match(/cch=([0-9a-f]{5})/);
      if (cchMatch) {
        const at = bodyBytes.indexOf(
          Buffer.from(`cch=${cchMatch[1]}`, "ascii"),
        );
        // `at` should always be >= 0 (the regex matched these exact bytes), but
        // guard defensively so a miss can never corrupt the body at offset 3.
        if (at >= 0) {
          const placeholder = Buffer.from(bodyBytes); // copy
          // Overwrite the 5 hex chars after "cch=" with "00000" (same length).
          Buffer.from("00000", "ascii").copy(placeholder, at + 4);
          captured = { body: placeholder, cch: cchMatch[1] };
        }
      }
    }

    res.writeHead(401, { "content-type": "application/json" });
    res.end(
      JSON.stringify({
        type: "error",
        error: {
          type: "authentication_error",
          message: "invalid x-api-key",
        },
      }),
    );
  });

  // Bind to an ephemeral port and read the assigned port back.
  await new Promise<void>((resolve) => {
    server.listen(0, "127.0.0.1", resolve);
  });
  const { port } = server.address() as AddressInfo;

  try {
    const proc = spawn(binaryPath, ["--print", "--bare", "-p", prompt], {
      env: {
        ...process.env,
        HOME: `${tmpDir}/home`,
        ANTHROPIC_API_KEY:
          "sk-ant-api03-fakekey1234567890abcdef1234567890abcdef1234567890abcdef",
        ANTHROPIC_BASE_URL: `http://127.0.0.1:${port}`,
        DISABLE_AUTOUPDATER: "1",
        DISABLE_UPDATES: "1",
      },
      cwd: `${tmpDir}/workdir`,
      stdio: "ignore",
    });

    // Wait up to 15s for the binary to make its request
    const timeout = setTimeout(() => proc.kill(), 15_000);
    await new Promise<void>((resolve) => proc.on("exit", () => resolve()));
    clearTimeout(timeout);
  } finally {
    await new Promise<void>((resolve) => server.close(() => resolve()));
  }

  return captured;
}

// ---------------------------------------------------------------------------
// Load oracle pairs from file
// ---------------------------------------------------------------------------

function loadOraclePairs(path: string): OraclePair[] {
  if (!existsSync(path)) {
    console.error(`Oracle file not found: ${path}`);
    process.exit(1);
  }

  // The JSON file stores each body as a (UTF-8) string. Convert to raw bytes.
  const raw: Array<{ body: string; cch: string }> = JSON.parse(
    readFileSync(path, "utf-8"),
  );
  if (!Array.isArray(raw) || raw.length === 0) {
    console.error("Oracle file must contain a non-empty JSON array");
    process.exit(1);
  }

  const pairs: OraclePair[] = [];
  for (const [i, pair] of raw.entries()) {
    if (!pair.body || !pair.cch) {
      console.error(`Oracle pair ${i} missing 'body' or 'cch' field`);
      process.exit(1);
    }
    if (!pair.body.includes("cch=00000")) {
      console.error(
        `Oracle pair ${i} body must contain 'cch=00000' placeholder`,
      );
      process.exit(1);
    }
    if (!/^[0-9a-f]{5}$/.test(pair.cch)) {
      console.error(
        `Oracle pair ${i} cch must be a 5-char lowercase hex string, got: ${pair.cch}`,
      );
      process.exit(1);
    }
    pairs.push({ body: Buffer.from(pair.body, "utf-8"), cch: pair.cch });
  }

  return pairs;
}

// ---------------------------------------------------------------------------
// Obtain binary
// ---------------------------------------------------------------------------

function detectPlatformPackage(): string {
  const platform = process.platform; // darwin, linux, win32
  const arch = process.arch; // x64, arm64
  return `@anthropic-ai/claude-code-${platform}-${arch}`;
}

function obtainBinary(version?: string, binaryPath?: string): string {
  if (binaryPath) {
    if (!existsSync(binaryPath)) {
      console.error(`Binary not found: ${binaryPath}`);
      process.exit(1);
    }
    return binaryPath;
  }

  const pkg = `${detectPlatformPackage()}@${version}`;
  const tmpDir = "/tmp/cch-seed-extract";
  mkdirSync(tmpDir, { recursive: true });

  console.log(`Downloading ${pkg} from npm...`);
  try {
    execSync(`npm pack ${pkg} --pack-destination ${tmpDir}`, {
      stdio: ["pipe", "pipe", "pipe"],
      cwd: tmpDir,
    });
  } catch (e) {
    console.error(
      `Failed to download ${pkg}: ${e instanceof Error ? e.message : String(e)}`,
    );
    process.exit(1);
  }

  // Find the tarball
  const tgz = readdirSync(tmpDir).find((f) =>
    /^anthropic-ai-claude-code-.*-.*\.tgz$/.test(f),
  );
  const tgzPath = tgz ? `${tmpDir}/${tgz}` : "";
  if (!tgzPath) {
    console.error("Could not find downloaded tarball");
    process.exit(1);
  }

  console.log("Extracting binary from tarball...");
  execSync(`tar xzf "${tgzPath}" -C "${tmpDir}"`, { stdio: "pipe" });

  const extractedBinary = `${tmpDir}/package/claude`;
  const extractedBinaryExe = `${tmpDir}/package/claude.exe`;
  const finalPath = existsSync(extractedBinary)
    ? extractedBinary
    : existsSync(extractedBinaryExe)
      ? extractedBinaryExe
      : null;

  if (!finalPath) {
    console.error(`Expected binary at ${extractedBinary} after extraction`);
    process.exit(1);
  }

  // Make executable
  try {
    execSync(`chmod +x "${finalPath}"`, { stdio: "pipe" });
  } catch {}

  // Clean up tarball
  try {
    unlinkSync(tgzPath);
  } catch {}

  return finalPath;
}

// ---------------------------------------------------------------------------
// Scan for seed
// ---------------------------------------------------------------------------

function testCandidate(seed: bigint, pairs: OraclePair[]): boolean {
  for (const pair of pairs) {
    const hash = xxHash64(pair.body, seed);
    const cch = (hash & 0xfffffn).toString(16).padStart(5, "0");
    if (cch !== pair.cch) return false;
  }
  return true;
}

function scan(
  binary: Buffer,
  pairs: OraclePair[],
  alignment: number,
): bigint | null {
  const candidates = Math.floor((binary.length - 7) / alignment);
  const label = alignment === 8 ? "8-byte aligned" : "1-byte aligned";
  console.log(
    `\nScanning ${candidates.toLocaleString()} ${label} candidates...`,
  );

  const start = performance.now();
  let tested = 0;
  const matches: Array<{ offset: number; seed: bigint }> = [];

  for (let offset = 0; offset + 8 <= binary.length; offset += alignment) {
    const candidate = binary.readBigUInt64LE(offset);
    if (candidate === 0n) continue;

    if (testCandidate(candidate, pairs)) {
      matches.push({ offset, seed: candidate });
      console.log(
        `  MATCH at offset 0x${offset.toString(16)}: seed = 0x${candidate.toString(16).padStart(16, "0")}`,
      );
      // With 2+ pairs, first match is almost certainly unique
      if (pairs.length >= 2) break;
    }
    tested++;
  }

  const elapsed = performance.now() - start;
  console.log(
    `Scan complete: ${tested.toLocaleString()} tested in ${(elapsed / 1000).toFixed(1)}s`,
  );

  if (matches.length === 0) {
    console.log("No matches found.");
    return null;
  }

  if (matches.length === 1 || pairs.length >= 2) {
    const m = matches[0];
    console.log(`\n✓ Found seed: 0x${m.seed.toString(16).padStart(16, "0")}`);
    return m.seed;
  }

  console.log(
    `\n⚠ Found ${matches.length} matches — add more oracle pairs to disambiguate`,
  );
  return null;
}

/**
 * Compile the bundled native scanner (scripts/cch-scan.c) with `cc -O3` into a
 * temp dir. Returns the executable path, or null when no C compiler is present
 * (the caller then falls back to the pure-JS scan). The compiled binary is
 * cached for the lifetime of the process.
 */
let nativeScannerPath: string | null | undefined;
function buildNativeScanner(): string | null {
  if (nativeScannerPath !== undefined) return nativeScannerPath;

  const src = join(fileURLToPath(new URL(".", import.meta.url)), "cch-scan.c");
  if (!existsSync(src)) {
    nativeScannerPath = null;
    return null;
  }

  const out = join(tmpdir(), "cch-scan");
  for (const compiler of ["cc", "gcc", "clang"]) {
    const r = spawnSync(compiler, ["-O3", "-o", out, src], {
      stdio: "ignore",
    });
    if (r.status === 0) {
      console.log(`Compiled native scanner with ${compiler}.`);
      nativeScannerPath = out;
      return out;
    }
  }

  console.log("No C compiler available — using JS scan.");
  nativeScannerPath = null;
  return null;
}

/**
 * Serialize oracle pairs into the line+raw-bytes format cch-scan.c reads:
 * "<cch-hex>\t<byte-length>\n" followed by the raw body bytes and a '\n'.
 * Bodies are passed as bytes (never argv) to avoid any encoding/quoting issues.
 */
function writePairsFile(pairs: OraclePair[]): string {
  const chunks: Buffer[] = [];
  for (const pair of pairs) {
    const body = Buffer.from(pair.body);
    chunks.push(Buffer.from(`${pair.cch}\t${body.length}\n`, "ascii"));
    chunks.push(body);
    chunks.push(Buffer.from("\n", "ascii"));
  }
  const path = join(tmpdir(), "cch-scan-pairs.txt");
  writeFileSync(path, Buffer.concat(chunks));
  return path;
}

/**
 * Run the native scanner over the binary at `binaryPath`. Returns the matching
 * seed, null when the scanner ran but found nothing, or `undefined` when the
 * native path is unavailable (so the caller falls back to the JS scan).
 */
function nativeScan(
  binaryPath: string,
  pairs: OraclePair[],
  alignment: number,
): bigint | null | undefined {
  const scanner = buildNativeScanner();
  if (!scanner) return undefined;

  const pairsFile = writePairsFile(pairs);
  const label = alignment === 8 ? "8-byte aligned" : "1-byte aligned";
  console.log(`\nNative scan (${label})...`);
  const start = performance.now();
  const r = spawnSync(scanner, [binaryPath, String(alignment), pairsFile], {
    encoding: "utf-8",
    maxBuffer: 1 << 20,
  });
  const elapsed = (performance.now() - start) / 1000;

  if (r.status !== 0) {
    console.warn(
      `Native scanner failed (${r.status}): ${r.stderr?.trim() ?? ""} — falling back to JS.`,
    );
    return undefined;
  }

  const out = (r.stdout ?? "").trim();
  const m = out.match(/^SEED (0x[0-9a-f]+)$/);
  if (m) {
    const seed = BigInt(m[1]);
    console.log(
      `✓ Native scan found seed in ${elapsed.toFixed(1)}s: 0x${seed.toString(16).padStart(16, "0")}`,
    );
    return seed;
  }
  console.log(`Native scan complete in ${elapsed.toFixed(1)}s: no match.`);
  return null;
}

function scanForSeed(
  binaryPath: string,
  binary: Buffer,
  pairs: OraclePair[],
): bigint | null {
  // Native scan first (orders of magnitude faster than the JS loop). 8-byte
  // aligned, then 1-byte aligned. `undefined` means the native path was
  // unavailable, so fall back to the JS scan; `null` means it ran and found
  // nothing (no point repeating the same work in JS).
  const native8 = nativeScan(binaryPath, pairs, 8);
  if (native8 !== undefined) {
    if (native8 !== null) return native8;
    const native1 = nativeScan(binaryPath, pairs, 1);
    if (native1 !== undefined) return native1;
  }

  // Pure-JS fallback (no compiler available or native path errored).
  let seed = scan(binary, pairs, 8);
  if (seed === null) {
    console.log("\nFalling back to 1-byte aligned scan...");
    seed = scan(binary, pairs, 1);
  }
  return seed;
}

/**
 * Claude Code reuses the same xxHash64 seed across long runs of consecutive
 * versions, so before scanning the whole binary we test the seeds we already
 * know against the freshly-captured oracle pairs. A match short-circuits the
 * expensive 230 MB binary scan. Distinct values are tested newest-first so the
 * most likely candidate (the current seed) is checked first.
 */
function tryKnownSeeds(pairs: OraclePair[]): bigint | null {
  if (pairs.length < 2) return null; // need 2 pairs to trust a match

  const distinct: bigint[] = [];
  // Object insertion order in cch.ts is oldest→newest; reverse for newest-first.
  for (const seed of Object.values(VERSION_SEEDS).reverse()) {
    if (!distinct.includes(seed)) distinct.push(seed);
  }
  if (distinct.length === 0) return null;

  console.log(
    `\nTesting ${distinct.length} known seed(s) against oracle pairs before scanning...`,
  );
  for (const seed of distinct) {
    if (testCandidate(seed, pairs)) {
      console.log(
        `✓ Known seed validates: 0x${seed.toString(16).padStart(16, "0")} — skipping binary scan.`,
      );
      return seed;
    }
  }
  console.log("No known seed matched — falling back to binary scan.");
  return null;
}

// ---------------------------------------------------------------------------
// Apply seed to cch.ts
// ---------------------------------------------------------------------------

/**
 * Turn a version string into the identifier used for its named seed constant,
 * e.g. "2.1.166" -> "SEED_2_1_166".
 */
function seedConstName(version: string): string {
  return `SEED_${version.replace(/[^0-9a-zA-Z]+/g, "_")}`;
}

/**
 * Find an existing `const SEED_xxx = 0x...n;` declaration whose value equals
 * `seedLiteral` (a normalized lowercase `0x...n` string). Returns the constant
 * name so a new version can reference it symbolically instead of repeating the
 * literal. Returns null when the seed value is not yet defined anywhere.
 */
function findSeedConstantByValue(
  content: string,
  seedLiteral: string,
): string | null {
  const declRe = /const\s+(SEED_[0-9A-Za-z_]+)\s*=\s*(0x[0-9a-f]+n)\s*;/gi;
  for (const m of content.matchAll(declRe)) {
    if (m[2].toLowerCase() === seedLiteral) return m[1];
  }
  return null;
}

function applySeed(
  version: string,
  seedHex: string,
  opts: { pin?: boolean } = {},
): void {
  const { pin = true } = opts;

  // Normalize the seed to a lowercase `0x...n` BigInt literal so it matches
  // the existing constants in cch.ts and stays Biome-clean.
  const rawHex = (seedHex.startsWith("0x") ? seedHex.slice(2) : seedHex)
    .replace(/n$/i, "")
    .toLowerCase();
  const seedLiteral = `0x${rawHex}n`;

  const cchPath = new URL("../packages/gateway/src/cch.ts", import.meta.url)
    .pathname;

  if (!existsSync(cchPath)) {
    console.error(`Cannot find cch.ts at: ${cchPath}`);
    process.exit(1);
  }

  let content = readFileSync(cchPath, "utf-8");

  // Decide how to reference the seed value: reuse an existing named constant
  // when the value is already defined, otherwise create a new one. This avoids
  // repeating the same literal across the many versions that share a seed.
  let constName = findSeedConstantByValue(content, seedLiteral);
  if (constName) {
    console.log(`Seed matches existing constant ${constName} — reusing it.`);
  } else {
    constName = seedConstName(version);
    // Insert the new constant immediately before the VERSION_SEEDS table.
    content = content.replace(
      /(\nexport const VERSION_SEEDS\b)/,
      `\nconst ${constName} = ${seedLiteral};\n$1`,
    );
    console.log(`New seed — added constant ${constName} = ${seedLiteral}.`);
  }

  // Insert or update the version -> constant mapping.
  if (content.includes(`"${version}"`)) {
    console.log(
      `Version ${version} already exists in VERSION_SEEDS. Updating...`,
    );
    const entryRe = new RegExp(
      `"${version.replace(/\./g, "\\.")}":\\s*[^,\\n]+`,
    );
    content = content.replace(entryRe, `"${version}": ${constName}`);
  } else {
    // Add before the "Future versions" comment.
    content = content.replace(
      /(\n\s*\/\/ Future versions: extract and add entries here\.)/,
      `\n  "${version}": ${constName},$1`,
    );
  }

  // Update WORKER_VERSION only when pinning (skip for backfill versions)
  if (pin) {
    content = content.replace(
      /const WORKER_VERSION = "[^"]+"/,
      `const WORKER_VERSION = "${version}"`,
    );
  }

  writeFileSync(cchPath, content);
  console.log(`Updated ${cchPath}:`);
  console.log(`  VERSION_SEEDS["${version}"] = ${constName} (${seedLiteral})`);
  if (pin) {
    console.log(`  WORKER_VERSION = "${version}"`);
  } else {
    console.log(`  WORKER_VERSION unchanged (--no-pin)`);
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const binaryPath = obtainBinary(args.version, args.binary);
  const binary = readFileSync(binaryPath);
  console.log(
    `Binary: ${binaryPath} (${(binary.length / 1024 / 1024).toFixed(1)} MB)`,
  );

  // Get oracle pairs: from file or auto-generate
  let pairs: OraclePair[];
  if (args.oracle) {
    pairs = loadOraclePairs(args.oracle);
    console.log(`Loaded ${pairs.length} oracle pair(s) from ${args.oracle}`);
    if (pairs.length < 2) {
      console.warn(
        "WARNING: <2 oracle pairs — expect false positives (~11 per pair)",
      );
    }
  } else {
    pairs = await generateOraclePairs(binaryPath, 2);
  }

  // Fast path: a previously-extracted seed often still applies to the new
  // version. Test known seeds against the oracle pairs before the full scan.
  let seed = tryKnownSeeds(pairs);

  // Slow path: scan the binary only when no known seed validated.
  if (seed === null) {
    seed = scanForSeed(binaryPath, binary, pairs);
  }

  if (seed !== null) {
    const hex = seed.toString(16).padStart(16, "0").toUpperCase();
    const version = args.version ?? "UNKNOWN";
    console.log(`
================================================================================
Add this to VERSION_SEEDS in packages/gateway/src/cch.ts:

  "${version}": 0x${hex}n,

Then update WORKER_VERSION if pinning to this version.

Or run:
  node scripts/extract-cch-seed.ts --apply "${version}" "0x${hex}"
================================================================================`);

    // Write JSON output if requested
    if (args.output) {
      const result = {
        version,
        seed: `0x${hex}`,
        seedDecimal: seed.toString(),
        oraclePairsUsed: pairs.length,
      };
      writeFileSync(args.output, JSON.stringify(result, null, 2));
      console.log(`Result written to ${args.output}`);
    }
  } else {
    console.error(
      "\nFailed to find seed. Possible causes:\n" +
        "  - Oracle pair generation failed (binary didn't make API calls)\n" +
        "  - Seed is constructed at runtime (not stored as raw bytes)\n" +
        "  - Binary is for the wrong platform/version",
    );
    process.exit(1);
  }
}

await main();
